name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: "docker build . --file Dockerfile --tag ${{ secrets.CR_REPO }}:$(cat Dockerfile | grep FROM | awk -F: '{print $(NF)}' | awk -F- '{print $1}')"
    - name: Login to ghcr.io
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${GITHUB_ACTOR} --password-stdin
    - name: Push to ghcr.io
      run: "docker push ${{ secrets.CR_REPO }}:$(cat Dockerfile | grep FROM | awk -F: '{print $(NF)}' | awk -F- '{print $1}')"
    - uses: actions/github-script@v3
      with:
        github-token: ${{secrets.CR_PAT}}
        script: |
          const i = await github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Actions Need Activities'
            body: 'cheers',
            labels: ['actions']
          })
          console.log(i)
          github.issues.update({
            issue_number: i.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'closed'
          })
